version: '3.4'

services:
  zookeeper-s:
    image: tools.radicalbit.io/zookeeper:3.4.11
    ports:
    - 2181:2181

  kafka-s:
    image: tools.radicalbit.io/kafka:0.10.2.1
    hostname: kafka-s
    ports:
    - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka-s
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-s:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
    - zookeeper-s
    volumes:
      - ./configs:/etc/configs
      - ./jars:/etc/jars

  zookeeper-d:
    image: tools.radicalbit.io/zookeeper:3.4.11
    ports:
    - 2182:2181

  kafka-d:
    image: tools.radicalbit.io/kafka:0.10.2.1
    hostname: kafka-d
    ports:
    - 9093:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka-d
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-d:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
    - zookeeper-d
    volumes:
    - ./configs:/etc/configs
    - ./jars:/etc/jars